# Generated by Django 4.2 on 2023-04-22 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_media_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='posts/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'pdf', 'png', 'webp', 'mp4', 'jpeg', 'gif'))]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(blank=True, max_length=9999, null=True, verbose_name='Post text'),
        ),
    ]
