# Generated by Django 4.2 on 2023-04-22 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_media_media_file_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='posts/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'pdf', 'png', 'webp', 'jpeg', 'mp4'))]),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=5),
        ),
    ]
