# Generated by Django 4.2 on 2023-04-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_media_media_file_alter_media_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='media_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='media_type',
            new_name='type',
        ),
    ]
