# Generated by Django 4.2 on 2023-04-24 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_media_file_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Post like creation date'),
            preserve_default=False,
        ),
    ]
