# Generated by Django 4.2 on 2023-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postlike_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='date_created',
            field=models.DateTimeField(verbose_name='Post like creation date'),
        ),
    ]
